symbols: [AAPL, MSFT, SPY]

data:
  duration: "5 D"       # Zeitraum für Historie
  barsize: "5 mins"     # Candle-Size
  what: TRADES          # TRADES | MIDPOINT | BID | ASK
  rth: true             # Regular Trading Hours

strategy:
  name: sma_cross
  fast: 10
  slow: 20

exec:
  mode: ask             # ask | auto | off
  asset: stock          # stock | forex | future
  order_type: MKT       # MKT | LMT | STP | STOP_LIMIT
  qty: 5
  tif: DAY              # Time in Force: DAY | GTC etc.

interval_sec: 120        # Bot-Loop Intervall (Sekunden)

telegram:
  enabled: true
  ask_mode: async        # blocking = wartet im Code | async = Buttons im Hintergrund
  ask_window_sec: 120    # Zeitfenster für Inline-Interaktion
